import { Sutra } from './types';

export const SUTRAS: Sutra[] = [
  // --- Beginner ---
  {
    id: 'ekadhikena',
    sanskritName: 'Ekadhikena Purvena',
    englishTranslation: 'By one more than the one before',
    description: 'Perfect for squaring numbers ending in 5 (e.g., 35², 85²).',
    difficulty: 'Beginner',
    colorClass: 'bg-emerald-900',
  },
  {
    id: 'nikhilam',
    sanskritName: 'Nikhilam Navatashcaramam Dashatah',
    englishTranslation: 'All from 9 and the last from 10',
    description: 'Ideal for multiplying numbers close to a base (e.g., 98 × 97) or subtracting from powers of 10.',
    difficulty: 'Beginner',
    colorClass: 'bg-indigo-900',
  },
  {
    id: 'multiply11',
    sanskritName: 'Antyayor Eva (x11)',
    englishTranslation: 'Only the last two',
    description: 'The magic method for multiplying any number by 11 instantly by adding neighbors.',
    difficulty: 'Beginner',
    colorClass: 'bg-pink-900',
  },
  {
    id: 'ekanyunena',
    sanskritName: 'Ekanyunena Purvena',
    englishTranslation: 'By one less than the one before',
    description: 'The specific method for multiplying by 9, 99, 999, etc. (e.g. 77 × 99).',
    difficulty: 'Beginner',
    colorClass: 'bg-teal-800',
  },
  {
    id: 'gunita',
    sanskritName: 'Gunita Samuccayah',
    englishTranslation: 'The product of the sum is the sum of the product',
    description: 'Using "Digital Roots" (Digit Sums) to instantly verify if a calculation is correct.',
    difficulty: 'Beginner',
    colorClass: 'bg-lime-900',
  },
  {
    id: 'sisyate',
    sanskritName: 'Sisyate Sesasamjnah',
    englishTranslation: 'The remainder remains constant',
    description: 'Used for checking answers via digital roots or finding remainders (e.g. casting out nines).',
    difficulty: 'Beginner',
    colorClass: 'bg-yellow-800',
  },

  // --- Intermediate ---
  {
    id: 'yavadunam',
    sanskritName: 'Yavadunam',
    englishTranslation: 'Whatever the deficiency',
    description: 'The fastest way to square numbers near a base like 100 or 1000 (e.g., 93², 104²).',
    difficulty: 'Intermediate',
    colorClass: 'bg-purple-900',
  },
  {
    id: 'urdhva',
    sanskritName: 'Urdhva Tiryagbhyam',
    englishTranslation: 'Vertically and Crosswise',
    description: 'The general formula for multiplication. Works for any two numbers.',
    difficulty: 'Intermediate',
    colorClass: 'bg-amber-700',
  },
  {
    id: 'antyayor',
    sanskritName: 'Antyayor Daskake Pi',
    englishTranslation: 'When the final digits add up to 10',
    description: 'Multiplication shortcut when last digits sum to 10 and previous parts are identical (e.g., 43 × 47).',
    difficulty: 'Intermediate',
    colorClass: 'bg-rose-900',
  },
  {
    id: 'paravartya',
    sanskritName: 'Paravartya Yojayet',
    englishTranslation: 'Transpose and Apply',
    description: 'Excellent for division where the divisor is slightly above a base (e.g. 112) or solving simple equations.',
    difficulty: 'Intermediate',
    colorClass: 'bg-cyan-900',
  },
  {
    id: 'sankalana',
    sanskritName: 'Sankalana Vyavakalanabhyam',
    englishTranslation: 'By addition and by subtraction',
    description: 'Solving simultaneous linear equations where x and y coefficients are swapped (e.g. 45x + 23y = 113).',
    difficulty: 'Intermediate',
    colorClass: 'bg-orange-900',
  },
  {
    id: 'purana',
    sanskritName: 'Puranapuranabhyam',
    englishTranslation: 'By the completion or non-completion',
    description: 'Used for algebraic identities or solving by completing the square/whole.',
    difficulty: 'Intermediate',
    colorClass: 'bg-fuchsia-800',
  },
  {
    id: 'vyasti',
    sanskritName: 'Vyastisamasti',
    englishTranslation: 'Specific and General',
    description: 'Use the average (mean) to solve problems, or solving specific equation types.',
    difficulty: 'Intermediate',
    colorClass: 'bg-blue-800',
  },
  {
    id: 'adyam',
    sanskritName: 'Adyamadyenantyamantyena',
    englishTranslation: 'The first by the first and the last by the last',
    description: 'Used for factorization of quadratic expressions or approximate multiplication.',
    difficulty: 'Intermediate',
    colorClass: 'bg-green-800',
  },
  {
    id: 'vestanam',
    sanskritName: 'Vestanam',
    englishTranslation: 'Osculation',
    description: 'Powerful tests for divisibility by prime numbers like 7, 13, 17, 19, etc.',
    difficulty: 'Intermediate',
    colorClass: 'bg-red-800',
  },
  {
    id: 'lopana',
    sanskritName: 'Lopanasthapanabhyam',
    englishTranslation: 'By alternate elimination and retention',
    description: 'Standard method for solving simultaneous linear equations by eliminating variables.',
    difficulty: 'Intermediate',
    colorClass: 'bg-gray-800',
  },

  // --- Advanced ---
  {
    id: 'vilokanam',
    sanskritName: 'Vilokanam',
    englishTranslation: 'By mere observation',
    description: 'Find Cube Roots of perfect cubes (up to 6 digits) just by looking at the number.',
    difficulty: 'Advanced',
    colorClass: 'bg-blue-900',
  },
  {
    id: 'anurupyena',
    sanskritName: 'Anurupyena',
    englishTranslation: 'Proportionality',
    description: 'Used for finding cubes of numbers (e.g. 13³) by maintaining the geometric ratio between digits.',
    difficulty: 'Advanced',
    colorClass: 'bg-fuchsia-900',
  },
  {
    id: 'shunyam',
    sanskritName: 'Shunyam Samyasamuccaye',
    englishTranslation: 'When the sum is the same, that sum is zero',
    description: 'A specific algebraic trick to solve complex-looking equations instantly by setting terms to zero.',
    difficulty: 'Advanced',
    colorClass: 'bg-slate-800',
  },
  {
    id: 'anurupye_shunyam',
    sanskritName: 'Anurupye Shunyamanyat',
    englishTranslation: 'If one is in ratio, the other is zero',
    description: 'Solving simultaneous equations where one variable is in a fixed ratio, implying the other variable is zero.',
    difficulty: 'Advanced',
    colorClass: 'bg-violet-900',
  },
  {
    id: 'calana',
    sanskritName: 'Calana Kalanabhyam',
    englishTranslation: 'Sequential motion',
    description: 'Methods related to calculus or finding roots of quadratic equations.',
    difficulty: 'Advanced',
    colorClass: 'bg-red-900',
  },
  {
    id: 'sesanyankena',
    sanskritName: 'Sesanyankena Caramena',
    englishTranslation: 'The remainders by the last digit',
    description: 'Expressing fractions like 1/19 or 1/7 as decimal expansions step-by-step.',
    difficulty: 'Advanced',
    colorClass: 'bg-sky-900',
  },
  {
    id: 'sopantyadvayamantyam',
    sanskritName: 'Sopantyadvayamantyam',
    englishTranslation: 'The ultimate and twice the penultimate',
    description: 'Solving specific algebraic fraction equations like 1/(x+a) + 1/(x+b) = ...',
    difficulty: 'Advanced',
    colorClass: 'bg-stone-800',
  },
  {
    id: 'gunakasamuccayah',
    sanskritName: 'Gunakasamuccayah',
    englishTranslation: 'The sum of the factors',
    description: 'Verifying algebraic factorization by comparing the sum of coefficients.',
    difficulty: 'Advanced',
    colorClass: 'bg-green-900',
  },
  {
    id: 'kevalaih',
    sanskritName: 'Kevalaih Saptakam Gunyat',
    englishTranslation: 'For 7 the multiplicand is 143',
    description: 'Special properties of the number 7 and the cyclic number 142857.',
    difficulty: 'Advanced',
    colorClass: 'bg-teal-900',
  },
  {
    id: 'samuccaya',
    sanskritName: 'Samuccayagunitah',
    englishTranslation: 'The product of the sums',
    description: 'Often paired with Gunita Samuccayah, used for verifying factors of expressions.',
    difficulty: 'Advanced',
    colorClass: 'bg-indigo-800',
  },
];
